// lib/supabase/database.types.ts
//
// This file is normally generated by Supabase CLI.
// It was missing in the repository and caused Vercel builds to fail.
//
// ✅ Quick unblock: permissive Database type.
// 🔁 Later: replace with generated types.

export type Database = any;
